In [1]:
# Python ≥3.5 is required
import sys
assert sys.version_info >= (3, 5)

# Scikit-Learn ≥0.20 is required
import sklearn
print("sklearn version: ", sklearn.__version__)
assert sklearn.__version__ >= "0.20"

try:
    # %tensorflow_version only exists in Colab.
    %tensorflow_version 2.x
    IS_COLAB = True
except Exception:
    IS_COLAB = False

# TensorFlow ≥2.0 is required
import tensorflow as tf
from tensorflow import keras
print("TF version: ", tf.__version__)
assert tf.__version__ >= "2.0"

if not tf.config.list_physical_devices('GPU'):
    print("No GPU was detected. CNNs can be very slow without a GPU.")
    if IS_COLAB:
        print("Go to Runtime > Change runtime and select a GPU hardware accelerator.")

# GPU test
print("GPU installed: ",tf.test.is_built_with_gpu_support())

# To prevent "CUDNN_STATUS_ALLOC_FAILED" error with GPUs
gpus = tf.config.experimental.list_physical_devices('GPU')
if gpus:
  try:
    # Currently, memory growth needs to be the same across GPUs
    for gpu in gpus:
      tf.config.experimental.set_memory_growth(gpu, True)
    logical_gpus = tf.config.experimental.list_logical_devices('GPU')
    print(len(gpus), "Physical GPUs,", len(logical_gpus), "Logical GPUs")
  except RuntimeError as e:
    # Memory growth must be set before GPUs have been initialized
    print(e)
    
# Common imports
import numpy as np
import os

# to make this notebook's output stable across runs
np.random.seed(42)
tf.random.set_seed(42)

# To plot pretty figures
%matplotlib inline
import matplotlib as mpl
import matplotlib.pyplot as plt
mpl.rc('axes', labelsize=14)
mpl.rc('xtick', labelsize=12)
mpl.rc('ytick', labelsize=12)

# Where to save the figures
PROJECT_ROOT_DIR = "."
CHAPTER_ID = "cnn"
IMAGES_PATH = os.path.join(PROJECT_ROOT_DIR, "images", CHAPTER_ID)
os.makedirs(IMAGES_PATH, exist_ok=True)

def save_fig(fig_id, tight_layout=True, fig_extension="png", resolution=300):
    path = os.path.join(IMAGES_PATH, fig_id + "." + fig_extension)
    print("Saving figure", fig_id)
    if tight_layout:
        plt.tight_layout()
    plt.savefig(path, format=fig_extension, dpi=resolution)
    
# Ignore useless warnings (see SciPy issue #5998)
import warnings
warnings.filterwarnings(action="ignore", message="^internal gelsd")

sklearn version:  1.0.2
TF version:  2.7.0
GPU installed:  True
1 Physical GPUs, 1 Logical GPUs

In [2]:
import pandas as pd

In [3]:
csv_test=pd.read_csv('./test.csv')

In [10]:
csv_test

,48,0,0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,...,0.614,0.615,0.616,0.617,0.618,0.619,0.620,0.621,0.622,0.623
0,48,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,48,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,48,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,48,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,48,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6094,90,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
6095,90,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
6096,90,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
6097,90,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
6098,90,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [13]:
np_test=csv_test.to_numpy()

array([ 48,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   8,   5,   0,   0,   5,   0,   0,   0,   0,   0,   0,   0,
         0,   1,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   6,   0,   0,   3,   4,   0,   0,   0,   0,   0,   1,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   1,   4,   4,   0,   0,   1,   6,   6,   0,   0,
         1,   2,   2,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   5,   2,   0,   0,   0,   0,   3,
         0,   0,   0,   1,   2,   2,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   1,   0,   8,  18,   3,
         0,   0,   1,   0,   0,   0,   1,   2,   1,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,  55,  67,  34,
        27,  32,  25,  20,  12,   7,   0,   0,   0,   1,   1,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,  26,  92,
        87,  26,  15,  34,  35,  29,  29,  19,   6,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
        87,  61,   8,   0,   8,   0,   0,   9,  41,  28,  11,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   6,   0,   2,   1,   1,   2,
         0,  16, 126,   9,   0,   1,   0,  16,   0,   0,   0,  52,  22,
         0,   5,   0,   0,   5,   0,   0,   0,   0,   1,   0,   4,   0,
         1,   0,   6,  47,  77,   7,  12,   2,   0,   0,   0,   6,  11,
        50,  17,   0,   5,   0,   0,   1,   0,   0,   0,   0,   0,   3,
         6,   0,   2,   0,  13,  81,  73,   2,   1,   6,   3,  16,   3,
         0,  35,  40,  10,   0,   3,   1,   3,   0,   0,   0,   0,   0,
         0,   6,   4,   0,   4,   0,  11,  90,  62,   0,   0,   4,   0,
         0,   0,  29,  38,  21,   3,   1,   0,   2,   5,   0,   0,   0,
         0,   0,   0,   6,   1,   0,   6,   0,   1,  68,  82,  16,   0,
         2,   2,   8,  28,  57,  23,   1,   0,   3,   0,   0,   3,   2,
         0,   0,   0,   0,   1,   3,   0,   0,   6,   1,   0,  34,  87,
        51,  25,  25,  40,  54,  43,  17,   6,   0,   1,   2,   0,   1,
         0,   5,   0,   0,   0,   0,   2,   0,   2,   0,   3,   5,   0,
         8,  17,  38,  45,  35,  20,  14,   8,   0,   0,   0,   5,   0,
         0,   5,   0,   5,   0,   0,   0,   0,   1,   0,   6,   0,   1,
         8,   0,   0,   0,   4,   0,   3,   3,   0,   4,   1,   2,   0,
         8,   0,   1,   8,   0,   4,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0], dtype=int64)

In [ ]:
plt.figure(figsize=(10,10))
for i in range(25):
    plt.subplot(5,5,i+1)
    plt.xticks([])
    plt.yticks([])
    plt.grid(False)
    plt.imshow(X_train[i,:,:,0], cmap=plt.cm.binary)
    plt.xlabel(class_names[y_train[i]])
plt.show()